"""Initial schema

Revision ID: ea84b5ce47e9
Revises:
Create Date: 2025-10-31 11:34:10.810798

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

from frozen_vault_backend.orm.enums.base_enums import ProductLocationEnum, ProductTypeEnum

# revision identifiers, used by Alembic.
revision: str = "ea84b5ce47e9"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "product_location",
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    op.create_index(op.f("ix_product_location_id"), "product_location", ["id"], unique=False)
    op.create_table(
        "product_type",
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    op.create_index(op.f("ix_product_type_id"), "product_type", ["id"], unique=False)
    op.create_table(
        "product",
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("description", sa.String(), nullable=False),
        sa.Column("quantity", sa.Integer(), nullable=False),
        sa.Column("unit", sa.String(), nullable=False),
        sa.Column("creation_date", sa.DateTime(), nullable=True),
        sa.Column("expiry_date", sa.DateTime(), nullable=True),
        sa.Column("image_location", sa.String(), nullable=True),
        sa.Column("product_type_id", sa.Integer(), nullable=False),
        sa.Column("product_location_id", sa.Integer(), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.CheckConstraint("quantity >= 1"),
        sa.CheckConstraint("unit IN ('g', 'boxes', 'bottles')", name="unit_check"),
        sa.CheckConstraint("expiry_date > creation_date", name="expiry_date_check"),
        sa.ForeignKeyConstraint(["product_location_id"], ["product_location.id"]),
        sa.ForeignKeyConstraint(["product_type_id"], ["product_type.id"]),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_product_id"), "product", ["id"], unique=False)

    # Add seed data
    # Insert product types
    product_type_table = sa.table("product_type", sa.column("name", sa.String))
    op.bulk_insert(product_type_table, [{"name": pt.value} for pt in ProductTypeEnum])

    # Insert product locations
    product_location_table = sa.table("product_location", sa.column("name", sa.String))
    op.bulk_insert(product_location_table, [{"name": pl.value} for pl in ProductLocationEnum])

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_product_id"), table_name="product")
    op.drop_table("product")
    op.drop_index(op.f("ix_product_type_id"), table_name="product_type")
    op.drop_table("product_type")
    op.drop_index(op.f("ix_product_location_id"), table_name="product_location")
    op.drop_table("product_location")
    # ### end Alembic commands ###
