site_name: FrozenVault Backend API Documentation
site_description: API documentation for the FrozenVault backend.
site_url: https://rchretien.github.io/frozen-vault
repo_url: https://github.com/rchretien/frozen-vault
repo_name: rchretien/frozen-vault

theme:
  name: material

nav:
  - Home: index.md

plugins:
  - search

markdown_extensions:
  - pymdownx.highlight
  - pymdownx.superfences
